spring:
  application:
    name: finpowerAPI
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html